error: package directory 'py_pubsub' does not exist
